services:
  userbot:
    build: .
    container_name: userbot4price
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # сессия Telethon — хранится на хосте, НЕ пересоздаётся при рестарте
      - ./userbot_session.session:/app/userbot_session.session
