services:
  userbot:
    build: .
    container_name: userbot4price
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # папка с сессией — хранится на хосте
      - ./data:/app/data
